name: hpos
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  sqflite: ^2.3.0
  core:
    path: package/core
  freezed:
  retrofit: 
  logger: any
  shared_preferences:
  dio: ^5.3.2
  json_annotation: ^4.8.1
  flutter_form_builder: ^9.1.1

  # core:
  #   git:
  #     url: https://github.com/Hwang2212/flutter_core
  #     ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  retrofit_generator: '>=5.0.0 <6.0.0'
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
